export type DestinationContent = {
  intro: string;
  vibe: string;
  bestTime: string;
  highlights: string[];
  neighborhoods: string[];
  foodToTry: string[];
  localTips: string[];
};

export const destinationContentBySlug: Record<string, DestinationContent> = {
  abidjan: {
    intro: "A fast-growing coastal capital where music, style, and late-night energy shape daily life.",
    vibe: "Creative, social, and high-energy.",
    bestTime: "November to April for drier weather.",
    highlights: ["Lagune Ebrié waterfront views", "Cocody art and culture spaces", "Live coupé-décalé nights"],
    neighborhoods: ["Cocody", "Plateau", "Marcory"],
    foodToTry: ["Attiéké with grilled fish", "Alloco", "Garba"],
    localTips: ["Plan extra time for traffic", "Use trusted ride apps at night", "Carry cash for smaller vendors"],
  },
  "addis-ababa": {
    intro: "A high-altitude capital with deep coffee culture, layered history, and strong creative momentum.",
    vibe: "Warm, community-driven, and culturally rich.",
    bestTime: "October to February for clearer skies.",
    highlights: ["National Museum", "Merkato market district", "Traditional coffee ceremonies"],
    neighborhoods: ["Bole", "Piazza", "Kazanchis"],
    foodToTry: ["Injera with tibs", "Shiro", "Doro wat"],
    localTips: ["Book museum visits early", "Learn a few Amharic greetings", "Evenings can be chilly year-round"],
  },
  abuja: {
    intro: "Nigeria's planned capital blends modern districts with nearby rock landscapes and vibrant food scenes.",
    vibe: "Polished, spacious, and steadily evolving.",
    bestTime: "November to March during the dry season.",
    highlights: ["Aso Rock viewpoints", "Jabi Lake", "Design-forward dining spots"],
    neighborhoods: ["Wuse", "Maitama", "Gwarinpa"],
    foodToTry: ["Suya", "Jollof rice", "Pepper soup"],
    localTips: ["Book transport ahead for peak hours", "Weekends are best for lakeside outings", "Carry a light layer for evening breeze"],
  },
  accra: {
    intro: "A coastal hub where contemporary art, nightlife, and history meet in one of West Africa's most dynamic cities.",
    vibe: "Bold, friendly, and design-conscious.",
    bestTime: "November to March for drier days.",
    highlights: ["Jamestown murals", "Labadi and Bojo beach escapes", "Independent fashion and concept stores"],
    neighborhoods: ["Osu", "Labone", "East Legon"],
    foodToTry: ["Waakye", "Red red", "Kelewele"],
    localTips: ["Plan beach days early", "Sunday brunch culture is huge", "Use local guides for heritage visits"],
  },
  amman: {
    intro: "A hilltop city of Roman history, modern cafés, and easy access to Jordan's desert and sea landscapes.",
    vibe: "Layered, hospitable, and calm.",
    bestTime: "March to May and September to November.",
    highlights: ["Citadel and Roman Theatre", "Rainbow Street walks", "Day trips to Dead Sea or Wadi Rum"],
    neighborhoods: ["Jabal Amman", "Abdoun", "Downtown"],
    foodToTry: ["Mansaf", "Falafel and hummus", "Kanafeh"],
    localTips: ["Wear good walking shoes for steep streets", "Taxi apps are easiest", "Fridays start later across many businesses"],
  },
  amsterdam: {
    intro: "Canal-lined streets, cycling culture, and world-class museums make Amsterdam endlessly walkable.",
    vibe: "Relaxed, progressive, and creative.",
    bestTime: "April to June or September for mild weather.",
    highlights: ["Canal belts and bridges", "Museumplein", "Independent design shops"],
    neighborhoods: ["Jordaan", "De Pijp", "Oud-West"],
    foodToTry: ["Stroopwafels", "Herring", "Bitterballen"],
    localTips: ["Rent bikes only if confident", "Book museums in advance", "Explore beyond the center for calmer evenings"],
  },
  athens: {
    intro: "Ancient landmarks sit beside rooftop bars and modern creative districts in one of Europe's oldest cities.",
    vibe: "Historic, gritty, and lively.",
    bestTime: "April to June and September to October.",
    highlights: ["Acropolis and Acropolis Museum", "Anafiotika lanes", "Sunset from Lycabettus Hill"],
    neighborhoods: ["Plaka", "Koukaki", "Psyrri"],
    foodToTry: ["Souvlaki", "Spanakopita", "Loukoumades"],
    localTips: ["Visit ruins early to avoid heat", "Late dinners are normal", "Pair city stay with a nearby island day trip"],
  },
  atlanta: {
    intro: "A major cultural and business center with deep Black history, music legacy, and excellent food scenes.",
    vibe: "Ambitious, warm, and culturally influential.",
    bestTime: "March to May or September to November.",
    highlights: ["BeltLine trails", "Civil Rights District", "Live music venues"],
    neighborhoods: ["Old Fourth Ward", "Midtown", "West End"],
    foodToTry: ["Fried chicken", "Soul food plates", "Peach cobbler"],
    localTips: ["Use MARTA for central routes", "Neighborhoods vary widely by vibe", "Brunch spots fill quickly on weekends"],
  },
  auckland: {
    intro: "A waterfront city between volcanic cones and island escapes, with an easy outdoor-meets-urban rhythm.",
    vibe: "Laid-back, scenic, and active.",
    bestTime: "December to March for summer weather.",
    highlights: ["Viaduct Harbour", "Waiheke day trips", "Mount Eden views"],
    neighborhoods: ["Ponsonby", "Parnell", "Devonport"],
    foodToTry: ["Fresh seafood", "Pacific fusion dishes", "Flat whites"],
    localTips: ["Weather shifts quickly", "Public ferries are great for day plans", "Book island trips ahead in summer"],
  },
  bali: {
    intro: "An island of temple rituals, surf towns, rice terraces, and fast-growing wellness communities.",
    vibe: "Spiritual, social, and scenic.",
    bestTime: "May to September for drier conditions.",
    highlights: ["Ubud rice fields", "Uluwatu cliffs", "Beach sunsets in Canggu"],
    neighborhoods: ["Ubud", "Canggu", "Uluwatu"],
    foodToTry: ["Nasi campur", "Babi guling", "Sate lilit"],
    localTips: ["Traffic can be slow", "Respect temple dress codes", "Early mornings are best for waterfalls and hikes"],
  },
  barcelona: {
    intro: "A city of modernist architecture, beach access, and neighborhood culture that rewards slow wandering.",
    vibe: "Artful, social, and Mediterranean.",
    bestTime: "May to June or September to October.",
    highlights: ["Sagrada Família", "Gothic Quarter", "Sunset at Bunkers del Carmel"],
    neighborhoods: ["El Born", "Gràcia", "Poblenou"],
    foodToTry: ["Pa amb tomàquet", "Patatas bravas", "Seafood paella"],
    localTips: ["Reserve major sights in advance", "Late dinners are standard", "Pickpocket awareness is important in crowded zones"],
  },
  beirut: {
    intro: "A resilient coastal capital where nightlife, food, and art continue to shape the city's identity.",
    vibe: "Expressive, layered, and welcoming.",
    bestTime: "April to June and September to November.",
    highlights: ["Corniche sunset walks", "Creative spaces in Mar Mikhael", "Historic downtown architecture"],
    neighborhoods: ["Gemmayzeh", "Mar Mikhael", "Hamra"],
    foodToTry: ["Mezze spreads", "Man'oushe", "Grilled seafood"],
    localTips: ["Check local updates before travel", "Best experiences are neighborhood-led", "Carry cash for smaller places"],
  },
  berlin: {
    intro: "A city defined by creative freedom, layered history, and constantly evolving cultural scenes.",
    vibe: "Experimental, intellectual, and open.",
    bestTime: "May to September for outdoor events.",
    highlights: ["Museum Island", "Tempelhofer Feld", "Nightlife and gallery circuits"],
    neighborhoods: ["Kreuzberg", "Neukölln", "Prenzlauer Berg"],
    foodToTry: ["Currywurst", "Döner", "Modern vegan cuisine"],
    localTips: ["Many spots are card-only, some cash-only", "Sundays are quieter shopping-wise", "Public transit is reliable late"],
  },
  bogota: {
    intro: "A high-altitude capital full of street art, mountain viewpoints, and one of Latin America's strongest food scenes.",
    vibe: "Vibrant, artistic, and energetic.",
    bestTime: "December to March for drier periods.",
    highlights: ["La Candelaria murals", "Monserrate views", "Gold Museum"],
    neighborhoods: ["Chapinero", "Zona G", "Usaquén"],
    foodToTry: ["Ajiaco", "Arepas", "Colombian coffee tastings"],
    localTips: ["Carry a light jacket daily", "Altitude can affect first-day pace", "Use ride apps after dark"],
  },
  casablanca: {
    intro: "A major Atlantic port with striking architecture, modern boulevards, and strong Moroccan identity.",
    vibe: "Urban, coastal, and business-forward.",
    bestTime: "March to May or September to November.",
    highlights: ["Hassan II Mosque", "Corniche coast", "Art deco city center"],
    neighborhoods: ["Maarif", "Habous", "Ain Diab"],
    foodToTry: ["Tagine", "Pastilla", "Mint tea"],
    localTips: ["Friday schedules can vary", "Dress smart-casual in business zones", "Combine city stay with nearby Rabat day trip"],
  },
  "cape-town": {
    intro: "A dramatic meeting of mountain and ocean with world-class wine routes, design spaces, and nature trails.",
    vibe: "Scenic, outdoorsy, and style-conscious.",
    bestTime: "November to March for summer conditions.",
    highlights: ["Table Mountain", "Cape Peninsula drives", "Woodstock art scene"],
    neighborhoods: ["Sea Point", "Gardens", "Woodstock"],
    foodToTry: ["Braai", "Cape Malay curries", "Fresh line fish"],
    localTips: ["Weather changes quickly", "Use trusted transport at night", "Book popular hikes early in peak season"],
  },
  dakar: {
    intro: "A creative coastal capital known for fashion, music, and powerful art scenes across the city.",
    vibe: "Expressive, warm, and culturally strong.",
    bestTime: "November to May for milder weather.",
    highlights: ["Île de Gorée", "Monument de la Renaissance Africaine", "Local fashion studios"],
    neighborhoods: ["Plateau", "Ngor", "Almadies"],
    foodToTry: ["Thieboudienne", "Yassa poulet", "Fresh grilled seafood"],
    localTips: ["French helps for navigation", "Sun can be strong year-round", "Music venues are best with local recommendations"],
  },
  dublin: {
    intro: "A walkable capital with literary history, cozy pubs, and easy coastal day trips.",
    vibe: "Friendly, story-rich, and compact.",
    bestTime: "May to September for longer daylight.",
    highlights: ["Trinity College and Book of Kells", "Temple Bar area", "Howth coastal walks"],
    neighborhoods: ["Stoneybatter", "Portobello", "Smithfield"],
    foodToTry: ["Irish stew", "Seafood chowder", "Soda bread"],
    localTips: ["Rain layers are essential", "Book popular pubs with live music", "Great base for train day trips"],
  },
  lagos: {
    intro: "A megacity of creativity, nightlife, and entrepreneurship where culture moves fast.",
    vibe: "Fast, ambitious, and electric.",
    bestTime: "November to March for drier weather.",
    highlights: ["Lekki arts and beach scene", "Live Afrobeats nights", "Design and fashion pop-ups"],
    neighborhoods: ["Lekki", "Victoria Island", "Yaba"],
    foodToTry: ["Jollof rice", "Suya", "Ofada and ayamase"],
    localTips: ["Plan around traffic windows", "Keep flexible daily schedules", "Local guides unlock the best scene access"],
  },
  lisbon: {
    intro: "Steep lanes, tiled facades, and Atlantic light make Lisbon ideal for slow city exploration.",
    vibe: "Romantic, textured, and easygoing.",
    bestTime: "March to June or September to November.",
    highlights: ["Miradouros", "Alfama streets", "Belém waterfront"],
    neighborhoods: ["Alfama", "Príncipe Real", "Chiado"],
    foodToTry: ["Pastéis de nata", "Bacalhau dishes", "Grilled sardines"],
    localTips: ["Wear shoes with grip for hills", "Tram routes get crowded early", "Sunset viewpoints fill fast"],
  },
  london: {
    intro: "A global city where neighborhood identities, world cuisine, and cultural institutions all coexist at scale.",
    vibe: "Diverse, layered, and constantly moving.",
    bestTime: "May to September for longer days.",
    highlights: ["Southbank riverside", "Free major museums", "Neighborhood markets"],
    neighborhoods: ["Shoreditch", "Notting Hill", "Brixton"],
    foodToTry: ["Sunday roast", "Global street food", "Afternoon tea twists"],
    localTips: ["Contactless transit saves time", "Museums are best early", "Weather can shift across a single day"],
  },
  "mexico-city": {
    intro: "An expansive capital with incredible food, history, and design—from ancient heritage to contemporary culture.",
    vibe: "Creative, dense, and endlessly rewarding.",
    bestTime: "March to May for warm, drier weather.",
    highlights: ["Historic Center", "Roma/Condesa creative districts", "Chapultepec park and museums"],
    neighborhoods: ["Roma Norte", "Condesa", "Coyoacán"],
    foodToTry: ["Tacos al pastor", "Chilaquiles", "Mole dishes"],
    localTips: ["Altitude affects first-day energy", "Reserve top restaurants early", "Use neighborhood-based planning to reduce travel time"],
  },
};

export function getDestinationContent(slug: string): DestinationContent | null {
  return destinationContentBySlug[slug] ?? null;
}
