export type CountryExplorerContinent =
  | "africa"
  | "asia"
  | "europe"
  | "northAmerica"
  | "southAmerica";

type MajorCity = {
  name: string;
  country: string;
};

const c = (name: string, country: string): MajorCity => ({ name, country });

const europe: MajorCity[] = [
  c("London", "UK"),
  c("Paris", "France"),
  c("Berlin", "Germany"),
  c("Madrid", "Spain"),
  c("Rome", "Italy"),
  c("Amsterdam", "Netherlands"),
  c("Brussels", "Belgium"),
  c("Vienna", "Austria"),
  c("Dublin", "Ireland"),
  c("Lisbon", "Portugal"),
  c("Stockholm", "Sweden"),
  c("Copenhagen", "Denmark"),
  c("Oslo", "Norway"),
  c("Helsinki", "Finland"),
  c("Warsaw", "Poland"),
  c("Prague", "Czech Republic"),
  c("Budapest", "Hungary"),
  c("Bucharest", "Romania"),
  c("Sofia", "Bulgaria"),
  c("Zagreb", "Croatia"),
  c("Athens", "Greece"),
  c("Barcelona", "Spain"),
  c("Milan", "Italy"),
  c("Munich", "Germany"),
  c("Frankfurt", "Germany"),
  c("Hamburg", "Germany"),
  c("Cologne", "Germany"),
  c("Zurich", "Switzerland"),
  c("Geneva", "Switzerland"),
  c("Manchester", "UK"),
  c("Birmingham", "UK"),
  c("Glasgow", "UK"),
  c("Lyon", "France"),
  c("Marseille", "France"),
  c("Naples", "Italy"),
  c("Turin", "Italy"),
  c("Seville", "Spain"),
  c("Valencia", "Spain"),
  c("Porto", "Portugal"),
  c("Kraków", "Poland"),
  c("Tallinn", "Estonia"),
  c("Riga", "Latvia"),
  c("Vilnius", "Lithuania"),
  c("Belgrade", "Serbia"),
  c("Ljubljana", "Slovenia"),
  c("Sarajevo", "Bosnia and Herzegovina"),
  c("Kyiv", "Ukraine"),
  c("Reykjavík", "Iceland"),
  c("Luxembourg", "Luxembourg"),
  c("Monaco", "Monaco"),
  c("Nicosia", "Cyprus"),
  c("Valletta", "Malta"),
];

const asiaRaws: MajorCity[] = [
  c("Tokyo", "Japan"),
  c("Yokohama", "Japan"),
  c("Osaka", "Japan"),
  c("Nagoya", "Japan"),
  c("Sapporo", "Japan"),
  c("Fukuoka", "Japan"),
  c("Seoul", "South Korea"),
  c("Busan", "South Korea"),
  c("Beijing", "China"),
  c("Shanghai", "China"),
  c("Guangzhou", "China"),
  c("Shenzhen", "China"),
  c("Chengdu", "China"),
  c("Hong Kong", "China"),
  c("Macau", "China"),
  c("Taipei", "Taiwan"),
  c("Kaohsiung", "Taiwan"),
  c("Delhi", "India"),
  c("Mumbai", "India"),
  c("Bengaluru", "India"),
  c("Chennai", "India"),
  c("Kolkata", "India"),
  c("Hyderabad", "India"),
  c("Pune", "India"),
  c("Singapore", "Singapore"),
  c("Bangkok", "Thailand"),
  c("Jakarta", "Indonesia"),
  c("Manila", "Philippines"),
  c("Ho Chi Minh City", "Vietnam"),
  c("Hanoi", "Vietnam"),
  c("Kuala Lumpur", "Malaysia"),
  c("Dhaka", "Bangladesh"),
  c("Karachi", "Pakistan"),
  c("Lahore", "Pakistan"),
  c("Islamabad", "Pakistan"),
  c("Kathmandu", "Nepal"),
  c("Colombo", "Sri Lanka"),
  c("Dubai", "UAE"),
  c("Abu Dhabi", "UAE"),
  c("Doha", "Qatar"),
  c("Riyadh", "Saudi Arabia"),
  c("Jeddah", "Saudi Arabia"),
  c("Mecca", "Saudi Arabia"),
  c("Kuwait City", "Kuwait"),
  c("Amman", "Jordan"),
  c("Beirut", "Lebanon"),
  c("Tel Aviv", "Israel"),
  c("Jerusalem", "Israel"),
  c("Tehran", "Iran"),
  c("Baghdad", "Iraq"),
  c("Erbil", "Iraq"),
  c("Baku", "Azerbaijan"),
  c("Tbilisi", "Georgia"),
  c("Yerevan", "Armenia"),
  c("Tashkent", "Uzbekistan"),
  c("Almaty", "Kazakhstan"),
  c("Astana", "Kazakhstan"),
  c("Ulaanbaatar", "Mongolia"),
  c("Phnom Penh", "Cambodia"),
  c("Yangon", "Myanmar"),
  c("Surabaya", "Indonesia"),
  c("Sydney", "Australia"),
  c("Melbourne", "Australia"),
  c("Brisbane", "Australia"),
  c("Perth", "Australia"),
  c("Auckland", "New Zealand"),
  c("Wellington", "New Zealand"),
  c("Kabul", "Afghanistan"),
  c("Muscat", "Oman"),
];

const dedupe = (list: MajorCity[], key: (m: MajorCity) => string): MajorCity[] => {
  const seen = new Set<string>();
  return list.filter((m) => {
    const k = key(m);
    if (seen.has(k)) return false;
    seen.add(k);
    return true;
  });
};

const asia = dedupe(asiaRaws, (m) => `${m.name}\0${m.country}`);

const africa: MajorCity[] = [
  c("Cairo", "Egypt"),
  c("Alexandria", "Egypt"),
  c("Giza", "Egypt"),
  c("Lagos", "Nigeria"),
  c("Kano", "Nigeria"),
  c("Ibadan", "Nigeria"),
  c("Abuja", "Nigeria"),
  c("Kinshasa", "DR Congo"),
  c("Khartoum", "Sudan"),
  c("Dar es Salaam", "Tanzania"),
  c("Nairobi", "Kenya"),
  c("Kampala", "Uganda"),
  c("Kigali", "Rwanda"),
  c("Addis Ababa", "Ethiopia"),
  c("Johannesburg", "South Africa"),
  c("Cape Town", "South Africa"),
  c("Pretoria", "South Africa"),
  c("Durban", "South Africa"),
  c("Casablanca", "Morocco"),
  c("Rabat", "Morocco"),
  c("Marrakech", "Morocco"),
  c("Algiers", "Algeria"),
  c("Tunis", "Tunisia"),
  c("Tripoli", "Libya"),
  c("Dakar", "Senegal"),
  c("Abidjan", "Côte d'Ivoire"),
  c("Accra", "Ghana"),
  c("Douala", "Cameroon"),
  c("Luanda", "Angola"),
  c("Maputo", "Mozambique"),
  c("Antananarivo", "Madagascar"),
  c("Harare", "Zimbabwe"),
  c("Lusaka", "Zambia"),
  c("Gaborone", "Botswana"),
  c("Windhoek", "Namibia"),
  c("Freetown", "Sierra Leone"),
  c("Conakry", "Guinea"),
  c("Monrovia", "Liberia"),
  c("Bamako", "Mali"),
  c("Ouagadougou", "Burkina Faso"),
  c("Niamey", "Niger"),
  c("Port Harcourt", "Nigeria"),
];

const northAmerica: MajorCity[] = [
  c("New York City", "USA"),
  c("Los Angeles", "USA"),
  c("Chicago", "USA"),
  c("Houston", "USA"),
  c("Phoenix", "USA"),
  c("Philadelphia", "USA"),
  c("San Antonio", "USA"),
  c("San Diego", "USA"),
  c("Dallas", "USA"),
  c("San Jose", "USA"),
  c("Austin", "USA"),
  c("San Francisco", "USA"),
  c("Seattle", "USA"),
  c("Denver", "USA"),
  c("Washington, D.C.", "USA"),
  c("Atlanta", "USA"),
  c("Boston", "USA"),
  c("Miami", "USA"),
  c("Toronto", "Canada"),
  c("Montreal", "Canada"),
  c("Vancouver", "Canada"),
  c("Calgary", "Canada"),
  c("Ottawa", "Canada"),
  c("Edmonton", "Canada"),
  c("Mexico City", "Mexico"),
  c("Guadalajara", "Mexico"),
  c("Monterrey", "Mexico"),
  c("Tijuana", "Mexico"),
  c("Cancún", "Mexico"),
  c("Guatemala City", "Guatemala"),
  c("San José", "Costa Rica"),
  c("Panama City", "Panama"),
  c("Havana", "Cuba"),
  c("San Juan", "Puerto Rico"),
  c("Nassau", "Bahamas"),
  c("Kingston", "Jamaica"),
  c("Port-au-Prince", "Haiti"),
  c("Managua", "Nicaragua"),
  c("Santo Domingo", "Dominican Republic"),
  c("Port of Spain", "Trinidad and Tobago"),
  c("Belize City", "Belize"),
];

const southAmerica: MajorCity[] = [
  c("São Paulo", "Brazil"),
  c("Rio de Janeiro", "Brazil"),
  c("Brasília", "Brazil"),
  c("Salvador", "Brazil"),
  c("Fortaleza", "Brazil"),
  c("Belo Horizonte", "Brazil"),
  c("Recife", "Brazil"),
  c("Buenos Aires", "Argentina"),
  c("Córdoba", "Argentina"),
  c("Rosario", "Argentina"),
  c("Lima", "Peru"),
  c("Bogotá", "Colombia"),
  c("Medellín", "Colombia"),
  c("Cali", "Colombia"),
  c("Barranquilla", "Colombia"),
  c("Santiago", "Chile"),
  c("Valparaíso", "Chile"),
  c("Caracas", "Venezuela"),
  c("Maracaibo", "Venezuela"),
  c("Guayaquil", "Ecuador"),
  c("Quito", "Ecuador"),
  c("La Paz", "Bolivia"),
  c("Santa Cruz de la Sierra", "Bolivia"),
  c("Asunción", "Paraguay"),
  c("Montevideo", "Uruguay"),
  c("Paramaribo", "Suriname"),
  c("Georgetown", "Guyana"),
];

const byContinent: Record<CountryExplorerContinent, MajorCity[]> = {
  europe,
  asia,
  africa,
  northAmerica,
  southAmerica,
};

export function getMajorCitiesByContinent(continent: CountryExplorerContinent): MajorCity[] {
  return byContinent[continent] ?? [];
}

function getAllMajorCitiesInWorld(): MajorCity[] {
  return [...europe, ...asia, ...africa, ...northAmerica, ...southAmerica].sort((a, b) =>
    a.name.localeCompare(b.name, "en"),
  );
}

export const totalMajorCityCount: number = getAllMajorCitiesInWorld().length;
