-- Seed 10 example local guides for /travel-guides marketplace cards.
-- Safe to re-run: duplicate slugs are ignored.

insert into public.cms_providers (
  slug,
  name,
  event_name,
  description,
  location,
  avatar_image_url,
  languages,
  specialties,
  contact_email,
  contact_phone,
  contact_website,
  banner_image_url,
  banner_image_alt,
  published_at
)
values
  (
    'guide-adeola-lagos-culture',
    'Adeola A.',
    'Lagos culture and street-life curator',
    'I host neighborhood-led experiences across Lagos, from market mornings to live music nights, with context on local history and modern creative scenes.',
    'Lagos, Nigeria',
    'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=600&q=80',
    '{"English","Yoruba"}'::text[],
    '{"Food tours","Live music","Street culture"}'::text[],
    'adeola@culturin-guides.demo',
    '+234-000-000-0001',
    'https://example.com',
    'https://images.unsplash.com/photo-1504609773099-104ff2d73d6b?auto=format&fit=crop&w=1600&q=80',
    'Lagos city scene at golden hour',
    '2025-04-01T09:00:00Z'::timestamptz
  ),
  (
    'guide-santi-barcelona-art',
    'Santi V.',
    'Barcelona art and architecture guide',
    'I design slow city walks focused on modernisme, independent galleries, and neighborhood food stops that avoid the usual tourist routes.',
    'Barcelona, Spain',
    'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=600&q=80',
    '{"Spanish","Catalan","English"}'::text[],
    '{"Architecture","Art spaces","Walking tours"}'::text[],
    'santi@culturin-guides.demo',
    '+34-000-000-0002',
    'https://example.com',
    'https://images.unsplash.com/photo-1558642452-9d2a7deb7f62?auto=format&fit=crop&w=1600&q=80',
    'Barcelona skyline and architecture',
    '2025-04-02T09:00:00Z'::timestamptz
  ),
  (
    'guide-nia-accra-creative',
    'Nia K.',
    'Accra creative industries host',
    'I connect guests to design studios, artist spaces, and contemporary makers while sharing practical context on local craft ecosystems.',
    'Accra, Ghana',
    'https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?auto=format&fit=crop&w=600&q=80',
    '{"English","Twi"}'::text[],
    '{"Design studios","Art markets","Creative economy"}'::text[],
    'nia@culturin-guides.demo',
    '+233-000-000-0003',
    'https://example.com',
    'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1600&q=80',
    'Accra city and coastal atmosphere',
    '2025-04-03T09:00:00Z'::timestamptz
  ),
  (
    'guide-zanele-cape-town-food',
    'Zanele M.',
    'Cape Town food and culture specialist',
    'I host culinary-first routes across Cape Town neighborhoods and nearby wine regions, with local producer stories woven throughout.',
    'Cape Town, South Africa',
    'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?auto=format&fit=crop&w=600&q=80',
    '{"English","Zulu"}'::text[],
    '{"Food experiences","Wine routes","Neighborhood stories"}'::text[],
    'zanele@culturin-guides.demo',
    '+27-000-000-0004',
    'https://example.com',
    'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1600&q=80',
    'Cape Town coast and sunset',
    '2025-04-04T09:00:00Z'::timestamptz
  ),
  (
    'guide-joao-lisbon-neighborhoods',
    'João R.',
    'Lisbon neighborhoods and music host',
    'I curate routes through Lisbon’s local districts, with fado, food, and design stops tailored to each guest’s interests and pace.',
    'Lisbon, Portugal',
    'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=600&q=80',
    '{"Portuguese","English"}'::text[],
    '{"Neighborhood tours","Music culture","Local dining"}'::text[],
    'joao@culturin-guides.demo',
    '+351-000-000-0005',
    'https://example.com',
    'https://images.unsplash.com/photo-1526154845684-aae17b6f2271?auto=format&fit=crop&w=1600&q=80',
    'Lisbon rooftops and tiled streets',
    '2025-04-05T09:00:00Z'::timestamptz
  ),
  (
    'guide-amina-marrakesh-medina',
    'Amina E.',
    'Marrakesh medina and crafts guide',
    'I lead immersive medina experiences focused on artisan traditions, architecture, and market etiquette that helps guests engage respectfully.',
    'Marrakesh, Morocco',
    'https://images.unsplash.com/photo-1541534401786-2077eed87a72?auto=format&fit=crop&w=600&q=80',
    '{"Arabic","French","English"}'::text[],
    '{"Craft traditions","Souk routes","Cultural etiquette"}'::text[],
    'amina@culturin-guides.demo',
    '+212-000-000-0006',
    'https://example.com',
    'https://images.unsplash.com/photo-1516026672322-bc52d61a55d9?auto=format&fit=crop&w=1600&q=80',
    'Marrakesh medina textures',
    '2025-04-06T09:00:00Z'::timestamptz
  ),
  (
    'guide-camila-mexico-city',
    'Camila G.',
    'Mexico City culture and food curator',
    'I build city experiences around architecture, independent food, and contemporary culture in walkable district loops.',
    'Mexico City, Mexico',
    'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=600&q=80',
    '{"Spanish","English"}'::text[],
    '{"Food walks","Architecture","Contemporary culture"}'::text[],
    'camila@culturin-guides.demo',
    '+52-000-000-0007',
    'https://example.com',
    'https://images.unsplash.com/photo-1503220317375-0ad578212403?auto=format&fit=crop&w=1600&q=80',
    'Mexico City urban landscape',
    '2025-04-07T09:00:00Z'::timestamptz
  ),
  (
    'guide-kenji-kyoto-slow',
    'Kenji T.',
    'Kyoto slow-city and heritage guide',
    'I host low-crowd Kyoto experiences centered on early mornings, neighborhood temples, and traditional café culture.',
    'Kyoto, Japan',
    'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=600&q=80',
    '{"Japanese","English"}'::text[],
    '{"Heritage walks","Slow travel","Tea culture"}'::text[],
    'kenji@culturin-guides.demo',
    '+81-000-000-0008',
    'https://example.com',
    'https://images.unsplash.com/photo-1492571350019-22de08371fd3?auto=format&fit=crop&w=1600&q=80',
    'Kyoto traditional street with lanterns',
    '2025-04-08T09:00:00Z'::timestamptz
  ),
  (
    'guide-lila-montreal-winter',
    'Lila B.',
    'Montreal winter culture host',
    'I curate winter-forward city programs: markets, food, design spaces, and neighborhood stories that make cold seasons feel vibrant.',
    'Montreal, Canada',
    'https://images.unsplash.com/photo-1544723795-3fb6469f5b39?auto=format&fit=crop&w=600&q=80',
    '{"French","English"}'::text[],
    '{"Winter city routes","Food culture","Design spaces"}'::text[],
    'lila@culturin-guides.demo',
    '+1-000-000-0009',
    'https://example.com',
    'https://images.unsplash.com/photo-1518548419970-58e3b4079ab2?auto=format&fit=crop&w=1600&q=80',
    'Montreal winter architecture',
    '2025-04-09T09:00:00Z'::timestamptz
  ),
  (
    'guide-mateo-buenos-aires',
    'Mateo S.',
    'Buenos Aires night and dance specialist',
    'I guide guests through tango social spaces, historic cafés, and neighborhood culture with a focus on local participation.',
    'Buenos Aires, Argentina',
    'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=600&q=80',
    '{"Spanish","English"}'::text[],
    '{"Tango culture","Night experiences","Café history"}'::text[],
    'mateo@culturin-guides.demo',
    '+54-000-000-0010',
    'https://example.com',
    'https://images.unsplash.com/photo-1509099836639-18ba1795216d?auto=format&fit=crop&w=1600&q=80',
    'Buenos Aires evening street scene',
    '2025-04-10T09:00:00Z'::timestamptz
  )
on conflict (slug) do nothing;
